version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install-terraform.sh configure-init.sh apply-terraform.sh # ma$
      - ./install-terraform.sh # install terraform
      - ./configure-init.sh # configure named profile

  build:
    commands:
      - ./apply-terraform.sh

